platform :ios, '9.0'
use_frameworks!

target 'Bounce' do

pod 'FBSDKCoreKit'

pod 'FBSDKLoginKit'

pod 'FBSDKShareKit'

pod 'KinveyKit'

pod 'MBProgressHUD', '~> 0.9.2'

end

target 'BounceTests' do

end

target 'BounceUITests' do

end
