platform :ios, '9.0'
use_frameworks!

target 'Bounce' do

pod 'RealmSwift'

pod 'Parse'

pod 'FBSDKCoreKit'

pod 'FBSDKLoginKit'

pod 'FBSDKShareKit'

pod 'ParseUI'

end

target 'BounceTests' do

end

target 'BounceUITests' do

end
