//
//  FBLoginVC.swift
//  Bounce
//
//  Created by Andrew Roach on 2/15/16.
//  Copyright © 2016 Andrew Roach. All rights reserved.
//

import UIKit
import FBSDKCoreKit
import FBSDKLoginKit


class FBLoginVC: UIViewController, FBSDKLoginButtonDelegate {
    
    
    @IBOutlet weak var profilePictureView: FBSDKProfilePictureView!
    
    
    @IBOutlet weak var nameLabel: UILabel!
    
    override func viewDidLoad() {
        self.view.backgroundColor = UIColor(red: 25.0 / 255.0, green: 181.0 / 255.0, blue: 146.0 / 255.0, alpha: 1.0)
        super.viewDidLoad()
        nameLabel.text = ""

        
        let loginButton = FBSDKLoginButton()
        loginButton.readPermissions = ["public_profile", "email", "user_friends"]
        loginButton.center = self.view.center
        loginButton.delegate = self
        self.view.addSubview(loginButton)
        
        login()

        
        NotificationCenter.default.addObserver(self, selector: #selector(FBLoginVC.configureContinueButton), name: NSNotification.Name(rawValue: BOUNCEUSERLOGGEDIN), object: nil)
        
    }
    
    @IBAction func doneButtonPressed(_ sender: UIBarButtonItem) {
        self.dismiss(animated: true, completion: {});

    }

    func configureContinueButton() {
            
        if FBSDKAccessToken.current() != nil && KCSUser.active() != nil {
            print("Logged in with Facebook & Kinvey")

        }
        else {
            print("Not Login")


        }
    }
    
    func login() {
        
        if FBSDKAccessToken.current() != nil {
            //facebook login succesfull
            let userFetcher = UserFetcher()
            userFetcher.createUser()
        }
    }
    
    func loginButton(_ loginButton: FBSDKLoginButton!, didCompleteWith result: FBSDKLoginManagerLoginResult!, error: Error!)
    {
        print("login to facebook complete")
        login()
    }
    
    func loginButtonDidLogOut(_ loginButton: FBSDKLoginButton!) {
        if KCSUser.active() != nil {
            KCSUser.active().logout()
        }
        configureContinueButton()
        print("User Logged Out")
        
    }
    
    
    
    @IBAction func continueToBounceButtonPressed(_ sender: UIButton) {
        //If there is no user, autogenerate a user:
//        if KCSUser.activeUser() == nil {
//            KCSUser.createAutogeneratedUser(
//                [
//                    KCSUserAttributeEmail : "kinvey@kinvey.com",
//                    KCSUserAttributeGivenname : "Arnold",
//                    KCSUserAttributeSurname : "Kinvey"
//                ],
//                completion: { (user: KCSUser!, errorOrNil: NSError!, result: KCSUserActionResult) -> Void in
//                    //do something
//                }
//            )
//        } else {
//            
//        }
        
    }
    
    
    
    
    
}
