//
//  FBLoginVC.swift
//  Bounce
//
//  Created by Andrew Roach on 2/15/16.
//  Copyright © 2016 Andrew Roach. All rights reserved.
//

import UIKit
import FBSDKCoreKit
import FBSDKLoginKit
import Fabric
import Crashlytics


class FBLoginVC: UIViewController, FBSDKLoginButtonDelegate {
    
    
    @IBOutlet weak var profilePictureView: FBSDKProfilePictureView!
    
    
    @IBOutlet weak var nameLabel: UILabel!
    
    override func viewDidLoad() {
        self.view.backgroundColor = UIColor(red: 25.0 / 255.0, green: 181.0 / 255.0, blue: 146.0 / 255.0, alpha: 1.0)
        super.viewDidLoad()
        nameLabel.text = ""

        
        let loginButton = FBSDKLoginButton()
        loginButton.readPermissions = ["public_profile", "email", "user_friends"]
        loginButton.center = self.view.center
        loginButton.delegate = self
        self.view.addSubview(loginButton)
        
        login()

        
        NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(FBLoginVC.configureContinueButton), name: BOUNCEUSERLOGGEDIN, object: nil)
        
    }
    
    @IBAction func doneButtonPressed(sender: UIBarButtonItem) {
        self.dismissViewControllerAnimated(true, completion: {});

    }

    func configureContinueButton() {
            
        if FBSDKAccessToken.currentAccessToken() != nil && KCSUser.activeUser() != nil {
            print("Logged in with Facebook & Kinvey")

        }
        else {
            print("Not Login")


        }
    }
    
    func login() {
        if FBSDKAccessToken.currentAccessToken() != nil {
            //facebook login succesfull
            let userFetcher = UserFetcher()
            userFetcher.createUser()
            
            Answers.logLoginWithMethod("Facebook",
                                       success: true,
                                       customAttributes: [:])
        }
        
    }
    
    func loginButton(loginButton: FBSDKLoginButton!, didCompleteWithResult result: FBSDKLoginManagerLoginResult!, error: NSError!)
    {
        login()
    }
    
    func loginButtonDidLogOut(loginButton: FBSDKLoginButton!) {
        if KCSUser.activeUser() != nil {
            KCSUser.activeUser().logout()
        }
        configureContinueButton()
        print("User Logged Out")
    }
    
    
    
    @IBAction func continueToBounceButtonPressed(sender: UIButton) {
        //If there is no user, autogenerate a user:
//        if KCSUser.activeUser() == nil {
//            KCSUser.createAutogeneratedUser(
//                [
//                    KCSUserAttributeEmail : "kinvey@kinvey.com",
//                    KCSUserAttributeGivenname : "Arnold",
//                    KCSUserAttributeSurname : "Kinvey"
//                ],
//                completion: { (user: KCSUser!, errorOrNil: NSError!, result: KCSUserActionResult) -> Void in
//                    //do something
//                }
//            )
//        } else {
//            
//        }
        
    }
    
    
    
    
    
}
